### ISSUE TITLE
Active Learning Trick?

### ISSUE THREAD

**Issue by JhuoW** [SongtaoLiu0823/LAGNN#11]
Hi, Songtao, 

Thanks for your amazing paper. I am particularly interested in the active learning technique described in Eq.10 of the paper. I find its implementation, as illustrated in the **cvae_pretrain.py**, somewhat complex. Because  it runs several GNN fine-tuning epochs during each mini-batch training iteration of the CVAE. 

Appendix B2 mentions that this active learning trick aids in addressing issues related to sampling from the long tail distribution, I find the explanation and the equation itself somewhat non-intuitive. Could you please provide a more detailed explanation of this concept? In particular, I am curious about the significance of the U-score in the overall results, because I think it is complicated. Did you do some ablation study about it? 

Thank you for your time and consideration.

**Comment by SongtaoLiu0823** [comment]
Hi,

Sorry for late response. I'm so busy this month. Yeah, we need multiple GNNs in cvae_pretrain.py. U-score is to evaluate the quality of samples. So we can use the active learning trick to prevent model generating samples from long-tail distribution. Our experiments (not in this paper) show with different hyper-paratermeters, our model can improve the performance. You also can refer to this paper: Gan data augmentation through active learning inspired sample acquisition.
