### ISSUE TITLE
Using local augumentation

### ISSUE THREAD

**Issue by Mugariya** [SongtaoLiu0823/LAGNN#3]
Hello,

I wanted to know how we can use Local augmentation to any GNN model in a plug-and-play manner?
If I have a GCN model, where do I make changes, like transformations to do it in a plug-and-play manner?

Thanks

**Comment by SongtaoLiu0823** [comment]
Thanks for your interest of our work.

As suggested in the paper, we concatenate the output of the first layer (AX, A\hat{X}) and feed to the second layer. So all you need to do is changing the first layer to concatenate the output.

And you also can concatenate X and \hat{X} firstly and feed to GCN. By doing so, there is no need to touch the architecture.

Best,
Songtao

**Comment by Mugariya** [comment]
Hello,
Thank you for your answer, how do I generate \hat{X}. I understand it's obtained by training CVAE model but if you could direct me to a file in the repo. That would be great. I want to use my own dataset and not any of the ones provided

Thanks

**Comment by SongtaoLiu0823** [comment]
> Hello, Thank you for your answer, how do I generate \hat{X}. I understand it's obtained by training CVAE model but if you could direct me to a file in the repo. That would be great. I want to use my own dataset and not any of the ones provided
> 
> Thanks

Given the learned CVAE model, we use the feature of the center node and latent variable sampled from standard Gaussian distribution as input for the decoder to obtain the generated \hat{X}. And we use cvae_pretrain.py to get the CVAE model.

Best,
Songtao
