### ISSUE TITLE
sorry  to bother you again

### ISSUE THREAD

**Issue by gaoshihao333** [SongtaoLiu0823/LAGNN#5]
in Citation/cvae_pretrain.py 33 lines  "x = features[adj[i].nonzero()[1]]"  intra [1] it should be [0]?

**Comment by SongtaoLiu0823** [comment]
Hi,
I print the information for you.


<img width="839" alt="WechatIMG727" src="https://user-images.githubusercontent.com/106496590/232157306-62e8d829-79ea-4219-8af6-1220f94b5875.png">

<img width="1105" alt="WechatIMG728" src="https://user-images.githubusercontent.com/106496590/232157330-4b61b57d-7f20-4480-bbf5-893fdb47c54d.png">

The adj object is of type sparse.csr.matrix, which is different from a PyTorch tensor. When extracting the i-th row from the adj matrix, the row index is assigned a value of 0, while the column index remains unchanged. So we use adj[i].nonzero()[1] to obtain the neighboring node number.

**Comment by gaoshihao333** [comment]
Thank you very much for you answer, I wish you hanppy every day!
