### ISSUE TITLE
new issue ...

### ISSUE THREAD

**Issue by gaoshihao333** [SongtaoLiu0823/LAGNN#6]
in  Citation/lagcn.py  132 line model(X_list+[features_normalized], adj_normalized), dim=-1), X_list is the enhanced features，right? My understanding is to generate features of neighbor nodes of node i based on node i, and these generated features are stored in X_list. In class LAGNN, X_list[K] is multiplied by A, but isn't X_list a features of the neighbor of node i，It's not a new feature of node i, right?Can you help me out? I'm not very good at coding. Excuse me. Thank you！

**Comment by SongtaoLiu0823** [comment]
Yeah, X_list it the enhanced features. 
Based on the features of node i as condition, we generate features of neighbor nodes.
Yeah, X_list is a features of the neighbor of node I instead of a new feature of node i.

**Comment by qingninggo** [comment]
Thank you again for your answers!
So you multiply the resulting neighbor node features by the original adjacency matrix. But in this case, how to explain? 
In my understanding, the position of node i in the 
generated features matrix corresponds to the features of node i in the original matrix, but now the position is the features of the neighbor of i, right?

**Comment by gaoshihao333** [comment]
Thank you again for your answers!
So you multiply the resulting neighbor node features by the original adjacency matrix. But in this case, how to explain?
In my understanding, the position of node i in the generated features matrix corresponds to the features of node i in the original matrix, but now the position is the features of the neighbor of i, right?

**Comment by SongtaoLiu0823** [comment]
Yeah, your understanding is right.
It is based on the homophily nature, where neighboring nodes have similar features.

**Comment by gaoshihao333** [comment]
All right, thanks! Have a nice evening!
