### ISSUE TITLE
SORRY , I've encountered an issue.

### ISSUE THREAD

**Issue by yinwang11** [SongtaoLiu0823/LAGNN#9]
Our dataset is not preprocessed into a cora-like format! and Do you have code for dataset preprocessing?

**Comment by SongtaoLiu0823** [comment]
I think you need to generate two files for adjacency matrix and feature matrix.

**Comment by 15235007059** [comment]
I read the code of cvae_pretrain.py closely, but I did not find the data processing part, and only the {}/data/ind.{}.{} data that has been processed can be read directly when I go to cvae_generate_citation. Can you explain the data preprocessing part in more detail? Or if it is convenient, you can add my wechat: 15235007059.

**Comment by chenyuqi7** [comment]
> Our dataset is not preprocessed into a cora-like format! and Do you have code for dataset preprocessing?
